version: '3.9'

services:
  drive-server-wip:
    image: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3000
    networks:
      - internxt
    env_file:
      - ./env.development
    command:
      - yarn start:dev

networks:
  internxt:
    name: internxt