version: '3.9'

services:
  drive-server-wip:
    build:
      context: .
      dockerfile: ./infrastructure/development.Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3000
    networks:
      - internxt
    env_file:
      - ./env.development

networks:
  internxt:
    name: internxt