name: run-tests
on:
  pull_request:
    branches:
      - "master"
jobs:
  run-tests:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Start PostgresSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'xCloud_test'
          postgresql user: 'admin'
          postgresql password: example

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'

      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc

      - name: Lint & Test
        run: yarn && yarn run test

      - name: Test E2E
        env:
          RDS_HOSTNAME: localhost
          RDS_DBNAME: xCloud_test
          RDS_USERNAME: admin
          RDS_PASSWORD: example
          RDS_PORT: 5432
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_MODE_SANDBOX: true
          APP_SEGMENT_KEY:  ${{ secrets.APP_SEGMENT_KEY }}
        run: yarn migrate:test && yarn run test:e2e

